### ISSUE TITLE
Протестить сонары

### ISSUE THREAD

**Issue by Mindtraveller** [AntonDershen/QuadScan#10]
1. Прикрутить сонары\сонар к ардуине. 
2. Имитировать полёт.
3. Зафиксировать результаты.
4. Сделать выводы. (в комментариях ниже)

Важно опрелелить скорость снятия результатов с сонаров + влияние вибрации на качество результатов.

**Comment by AntonDershen** [comment]
1. Были произведены тесты(на дальность измерения, и чувствительность к вибрации)
2. Оценены результаты тестов.

Сонары работают хорошо на расстоянии 2 метра, чувствительность к вибрации невысокая.
