### ISSUE TITLE
Формат данных для построения карты

### ISSUE THREAD

**Issue by Mindtraveller** [AntonDershen/QuadScan#12]
Необходимо определить формат данных, передаваемых коптером на копьютер для построения карты

**Comment by alexlazyman** [comment]
Были проанализированы возможности квадракоптера и минимум данных, которые необходимы для визуализации карты.

И получившийся формат таков:
1) Смещение по оси X, Y, Z - смещение квадракоптера относительно предыдущего месторасположения.
2) Данные с сонаров - расстояния до препятствий (0 <= R <= 2м) или препятствий нет (R > 2м), доверительный радиус этой точки 10 - 50 см.
3) Поворот квадракоптера - поворот квадракоптера относительно нормали, которая определяется при первом получении данных от квадракоптера.

Также необходимы данные для инициализации:
1) Количество сонаров - сонары, которые будут присылать данные.
2) Направления сонаров - смещения в градусах, относительно нуля.

Данные для инициализации могут быть по умолчанию и никогда не изменяться.
