### ISSUE TITLE
Выбор платформы для написание программы для построения плана здания

### ISSUE THREAD

**Issue by Mindtraveller** [AntonDershen/QuadScan#21]
Необходимо определить платформу, на которой будет реализована программа для построения карты.

**Comment by alexlazyman** [comment]
Построение карты будет происходить в редакторе Unity.
Преимущества этого редактора:
1) крос-платформенность (Android, Windows, Linux и много других платформ)
2) этот редактор предназначен для создания 2D и 3D графики
3) в нём присутствует очень удобный и полезный набор инструментов
4) поддерживает ООП на языке C#, JavaScript

**Comment by alexlazyman** [comment]
Так как Unity полностью поддерживает как C#, так и JS, то я выберу C#, т. к. опыта написания проектов на нём больше.
