### ISSUE TITLE
Покупка квадрокоптера

### ISSUE THREAD

**Issue by evheny0** [AntonDershen/QuadScan#7]
http://catalog.onliner.by/radiocontrolair/syma/syma_x5c

**Comment by Mindtraveller** [comment]
поговорили с продавцом, он подсказал пару идей. проверим, решим что делать дальше.

**Comment by Mindtraveller** [comment]
Заказали 2 Pairs 5030 RC Airplane 2 - Blade H250 Glassy Carbon Mini Multicopter DIY Accessories  -  AS THE PICTURE 1
+
Lion Power 11.1V 1500mAh 40C Lipo High Capacity Battery
